[libdefaults]
  default_realm = KUPAVA.BY
  dns_lookup_realm = false
  dns_lookup_kdc = true
  ticket_lifetime = 24h
  renew_lifetime = 7d
  forwardable = true

[realms]
  KUPAVA.BY = {
    kdc = forseti.kupava.by
    admin_server = forseti.kupava.by
  }

[domain_realm]
  .kupava.by = KUPAVA.BY
  kupava.by = KUPAVA.BY
